-- The active Cyber Lab IN schema is managed exclusively by the tracked files in:
--   cyberscout-server/db/migrations/
--
-- Do not maintain a second schema definition in this file. Apply the canonical
-- schema to Supabase with `npm run db:migrate --prefix cyberscout-server` after
-- setting DATABASE_URL to the Supabase PostgreSQL connection string.
