import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Award,
  BookOpen,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Circle,
  Clock,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Globe2,
  GraduationCap,
  Info,
  Link as LinkIcon,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Network,
  Phone,
  PlayCircle,
  Route,
  RefreshCw,
  Search,
  SearchCheck,
  Send,
  ShieldCheck,
  UserRound,
  Users,
  X,
} from 'lucide-react'

const icons = {
  account_circle: UserRound,
  account_tree: Network,
  apartment: Building2,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  check: Check,
  check_circle: CheckCircle2,
  close: X,
  description: FileText,
  download: Download,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  external_link: ExternalLink,
  forum: MessageCircle,
  groups: Users,
  info: Info,
  language: Globe2,
  link: LinkIcon,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  mail: Mail,
  manage_search: SearchCheck,
  menu: Menu,
  phone: Phone,
  play_circle: PlayCircle,
  route: Route,
  refresh: RefreshCw,
  schedule: Clock,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  view_module: BookOpen,
  visibility: Eye,
  visibility_off: EyeOff,
  workspace_premium: Award,
}

export default function SiteIcon({ name, size = 18, strokeWidth = 2, ...props }) {
  const Icon = icons[name] || Circle
  return <Icon width={size} height={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />
}
