import {
  AlertCircle,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  Award,
  Bell,
  BookOpen,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleHelp,
  CircleX,
  Clock,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Globe2,
  GraduationCap,
  Hand,
  Headset,
  Info,
  LayoutDashboard,
  Link as LinkIcon,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Network,
  Newspaper,
  Phone,
  Play,
  PlayCircle,
  Presentation,
  Route,
  RefreshCw,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Timer,
  Trophy,
  Bot,
  UserRound,
  Users,
  Video,
  VideoOff,
  Wrench,
  X,
  ChartNoAxesCombined,
} from 'lucide-react'

const icons = {
  account_circle: UserRound,
  account_tree: Network,
  apartment: Building2,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  analytics: ChartNoAxesCombined,
  back_hand: Hand,
  build: Wrench,
  cancel: CircleX,
  check: Check,
  check_circle: CheckCircle2,
  close: X,
  chevron_right: ChevronRight,
  dashboard: LayoutDashboard,
  description: FileText,
  download: Download,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  external_link: ExternalLink,
  forum: MessageCircle,
  groups: Users,
  group: Users,
  help: CircleHelp,
  info: Info,
  language: Globe2,
  link: LinkIcon,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  manage_search: SearchCheck,
  menu: Menu,
  mic: Mic,
  mic_off: MicOff,
  notifications: Bell,
  payments: CreditCard,
  picture_as_pdf: FileText,
  phone: Phone,
  play_circle: PlayCircle,
  play_arrow: Play,
  person: UserRound,
  presentation: Presentation,
  radio_button_unchecked: Circle,
  route: Route,
  refresh: RefreshCw,
  schedule: Clock,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  send: Send,
  security: ShieldCheck,
  settings: Settings,
  shield: Shield,
  shield_lock: ShieldCheck,
  smart_toy: Bot,
  support_agent: Headset,
  timer: Timer,
  leaderboard: Trophy,
  article: Newspaper,
  video_camera_front: Video,
  video_chat: Video,
  videocam_off: VideoOff,
  view_module: BookOpen,
  visibility: Eye,
  visibility_off: EyeOff,
  workspace_premium: Award,
}

export default function SiteIcon({ name, size = 18, strokeWidth = 2, className = '', ...props }) {
  const Icon = icons[name] || Circle
  return <Icon className={`site-icon ${className}`.trim()} width={size} height={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />
}
