import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { closeDatabase, pool } from './index.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const migrationsDir = path.resolve(__dirname, '../../db/migrations')

async function assertCompatibleExistingSchema(client) {
  const result = await client.query(`
    SELECT table_name, data_type
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND column_name = 'id'
      AND table_name IN ('users', 'courses')
  `)

  const incompatible = result.rows.filter(
    row => !['text', 'character varying', 'character'].includes(row.data_type),
  )
  if (!incompatible.length) return

  const details = incompatible.map(row => `${row.table_name}.id is ${row.data_type}`).join(', ')
  throw new Error(
    `Existing Supabase schema is incompatible with the tracked Cyber Lab IN migrations (${details}). `
      + 'No migrations were applied. Back up the database and complete an explicit data migration before deploying.',
  )
}

export async function runPendingMigrations({ log = false } = {}) {
  const client = await pool.connect()
  try {
    await client.query("SELECT pg_advisory_lock(hashtext('cyberlabin_schema_migrations'))")
    await assertCompatibleExistingSchema(client)
    await client.query(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL UNIQUE,
        applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `)

    const files = (await fs.readdir(migrationsDir)).filter(file => file.endsWith('.sql')).sort()
    const appliedRows = await client.query('SELECT name FROM schema_migrations')
    const applied = new Set(appliedRows.rows.map(row => row.name))
    const appliedNow = []

    for (const file of files) {
      if (applied.has(file)) continue
      const sql = await fs.readFile(path.join(migrationsDir, file), 'utf8')
      await client.query('BEGIN')
      try {
        await client.query(sql)
        await client.query('INSERT INTO schema_migrations (name) VALUES ($1)', [file])
        await client.query('COMMIT')
        appliedNow.push(file)
        if (log) console.log(`Applied PostgreSQL migration: ${file}`)
      } catch (error) {
        await client.query('ROLLBACK')
        throw new Error(`Migration ${file} failed: ${error.message}`)
      }
    }

    return appliedNow
  } finally {
    await client.query("SELECT pg_advisory_unlock(hashtext('cyberlabin_schema_migrations'))").catch(() => {})
    client.release()
  }
}

const executedDirectly = process.argv[1] && path.resolve(process.argv[1]) === __filename
if (executedDirectly) {
  try {
    const applied = await runPendingMigrations({ log: true })
    if (!applied.length) console.log('No pending PostgreSQL migrations.')
    console.log('PostgreSQL database migrations are current.')
  } finally {
    await closeDatabase()
  }
}
