/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#000515',
        'on-primary': '#ffffff',
        'primary-container': '#0a1e3d',
        'on-primary-container': '#7586ab',
        'secondary': '#7C3AED',
        'on-secondary': '#ffffff',
        'secondary-container': '#A78BFA',
        'on-secondary-container': '#4C1D95',
        'tertiary': '#00041a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#111d3d',
        'on-tertiary-container': '#7a85ab',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        'surface': '#f7f9fb',
        'on-surface': '#191c1e',
        'surface-variant': '#e0e3e5',
        'on-surface-variant': '#44474e',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'outline': '#75777f',
        'outline-variant': '#c5c6cf',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b5c7ee',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#b5c7ee',
        'on-primary-fixed': '#061b3a',
        'on-primary-fixed-variant': '#354768',
        'secondary-fixed': '#EDE9FE',
        'secondary-fixed-dim': '#8B5CF6',
        'on-secondary-fixed': '#2E1065',
        'on-secondary-fixed-variant': '#4C1D95',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#bac5ee',
        'on-tertiary-fixed': '#0e1a3a',
        'on-tertiary-fixed-variant': '#3b4668',
        'surface-tint': '#4d5e81',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin': '32px',
        'gutter': '24px',
        'unit': '8px',
      },
      maxWidth: {
        'container': '1280px',
      },
      fontFamily: {
        'space-grotesk': ['Space Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'code-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      boxShadow: {
        'card': '0 1px 3px rgba(10,30,61,0.06)',
        'card-hover': '0 4px 12px rgba(10,30,61,0.12)',
      },
    },
  },
  plugins: [],
}
